In [1]:
import numpy as np
import pandas as pd

In [2]:
# df=pd.read_csv("C:\\Users\\subha\\OneDrive\\Documents\\covid_toy.csv")
# df

In [3]:
df=pd.read_csv("C:\\Users\\hp\\Downloads\\cancer patient data sets.csv")
df

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0        0         P1   33       1              2            4             5   
1        1        P10   17       1              3            1             5   
2        2       P100   35       1              4            5             6   
3        3      P1000   37       1              7            7             7   
4        4       P101   46       1              6            8             7   
..     ...        ...  ...     ...            ...          ...           ...   
995    995       P995   44       1              6            7             7   
996    996       P996   37       2              6            8             7   
997    997       P997   25       2              4            5             6   
998    998       P998   18       2              6            8             7   
999    999       P999   47       1              6            5             6   

     chronic Lung Disease  Smoking  Chest Pain  Coughing of Blood  \
0                       2        3           2                  4   
1                       2        2           2                  3   
2                       4        2           4                  8   
3                       7        7           7                  8   
4                       6        8           7                  9   
..                    ...      ...         ...                ...   
995                     6        7           7                  7   
996                     6        7           7                  7   
997                     4        2           4                  8   
998                     6        8           7                  9   
999                     4        2           4                  8   

     Shortness of Breath  Dry Cough  Length Of Stay   Level  
0                      2          3               4     Low  
1                      7          7               2  Medium  
2                      9          7               2    High  
3                      3          7               5    High  
4                      4          2               3    High  
..                   ...        ...             ...     ...  
995                    2          5               3    High  
996                    5          1               4    High  
997                    9          7               2    High  
998                    4          2               3    High  
999                    9          7               2    High  

[1000 rows x 15 columns]

In [4]:
df1=pd.read_csv("C:\\Users\\hp\\Downloads\\hospital.csv",usecols=["glucose","pulse"])
df1

glucose  pulse
0    192.476918     96
1     94.078507     61
2    130.530524     64
3    163.377028     76
4     94.886654     67
..          ...    ...
995   99.229834     73
996  215.856429     84
997  178.394463     75
998  192.157665     71
999  124.384981     75

[1000 rows x 2 columns]

In [5]:
df2=np.hstack((df,df1))
df2

# stacked_array = np.hstack((array1, array2))



array([[0, 'P1', 33, ..., 'Low', 192.4769177, 96.0],
       [1, 'P10', 17, ..., 'Medium', 94.07850731, 61.0],
       [2, 'P100', 35, ..., 'High', 130.5305238, 64.0],
       ...,
       [997, 'P997', 25, ..., 'High', 178.3944633, 75.0],
       [998, 'P998', 18, ..., 'High', 192.1576654, 71.0],
       [999, 'P999', 47, ..., 'High', 124.3849813, 75.0]], dtype=object)

In [6]:
df1.columns

Index(['glucose', 'pulse'], dtype='object')

In [7]:
df=pd.DataFrame(df2,columns=['index', 'Patient Id', 'Age', 'Gender', 'Air Pollution', 'Alcohol use',
       'Dust Allergy', 'chronic Lung Disease', 'Smoking', 'Chest Pain',
       'Coughing of Blood', 'Shortness of Breath', 'Dry Cough',
       'Length Of Stay', 'Level','glucose', 'pulse'])
df

index Patient Id Age Gender Air Pollution Alcohol use Dust Allergy  \
0       0         P1  33      1             2           4            5   
1       1        P10  17      1             3           1            5   
2       2       P100  35      1             4           5            6   
3       3      P1000  37      1             7           7            7   
4       4       P101  46      1             6           8            7   
..    ...        ...  ..    ...           ...         ...          ...   
995   995       P995  44      1             6           7            7   
996   996       P996  37      2             6           8            7   
997   997       P997  25      2             4           5            6   
998   998       P998  18      2             6           8            7   
999   999       P999  47      1             6           5            6   

    chronic Lung Disease Smoking Chest Pain Coughing of Blood  \
0                      2       3          2                 4   
1                      2       2          2                 3   
2                      4       2          4                 8   
3                      7       7          7                 8   
4                      6       8          7                 9   
..                   ...     ...        ...               ...   
995                    6       7          7                 7   
996                    6       7          7                 7   
997                    4       2          4                 8   
998                    6       8          7                 9   
999                    4       2          4                 8   

    Shortness of Breath Dry Cough Length Of Stay   Level     glucose pulse  
0                     2         3              4     Low  192.476918  96.0  
1                     7         7              2  Medium   94.078507  61.0  
2                     9         7              2    High  130.530524  64.0  
3                     3         7              5    High  163.377028  76.0  
4                     4         2              3    High   94.886654  67.0  
..                  ...       ...            ...     ...         ...   ...  
995                   2         5              3    High   99.229834  73.0  
996                   5         1              4    High  215.856429  84.0  
997                   9         7              2    High  178.394463  75.0  
998                   4         2              3    High  192.157665  71.0  
999                   9         7              2    High  124.384981  75.0  

[1000 rows x 17 columns]

In [8]:
df = df.drop(columns=['index', 'Patient Id'])
df

Age Gender Air Pollution Alcohol use Dust Allergy chronic Lung Disease  \
0    33      1             2           4            5                    2   
1    17      1             3           1            5                    2   
2    35      1             4           5            6                    4   
3    37      1             7           7            7                    7   
4    46      1             6           8            7                    6   
..   ..    ...           ...         ...          ...                  ...   
995  44      1             6           7            7                    6   
996  37      2             6           8            7                    6   
997  25      2             4           5            6                    4   
998  18      2             6           8            7                    6   
999  47      1             6           5            6                    4   

    Smoking Chest Pain Coughing of Blood Shortness of Breath Dry Cough  \
0         3          2                 4                   2         3   
1         2          2                 3                   7         7   
2         2          4                 8                   9         7   
3         7          7                 8                   3         7   
4         8          7                 9                   4         2   
..      ...        ...               ...                 ...       ...   
995       7          7                 7                   2         5   
996       7          7                 7                   5         1   
997       2          4                 8                   9         7   
998       8          7                 9                   4         2   
999       2          4                 8                   9         7   

    Length Of Stay   Level     glucose pulse  
0                4     Low  192.476918  96.0  
1                2  Medium   94.078507  61.0  
2                2    High  130.530524  64.0  
3                5    High  163.377028  76.0  
4                3    High   94.886654  67.0  
..             ...     ...         ...   ...  
995              3    High   99.229834  73.0  
996              4    High  215.856429  84.0  
997              2    High  178.394463  75.0  
998              3    High  192.157665  71.0  
999              2    High  124.384981  75.0  

[1000 rows x 15 columns]

In [9]:
df.isnull().sum()

Age                     0
Gender                  0
Air Pollution           0
Alcohol use             0
Dust Allergy            0
chronic Lung Disease    0
Smoking                 0
Chest Pain              0
Coughing of Blood       0
Shortness of Breath     0
Dry Cough               0
Length Of Stay          0
Level                   0
glucose                 0
pulse                   0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x = df.drop(columns = ['Level'])
y=df['Level']

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [14]:
lb = LabelEncoder()
y_train_label = lb.fit_transform( y_train)
y_train_label
y_test_label = lb.fit_transform( y_test)
y_test_label

array([2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 2,
       1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2,
       2, 1, 1, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 2,
       0, 0, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1,
       0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0, 2, 2, 2,
       2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 2,
       1, 0, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0,
       2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 2])

In [15]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import PolynomialFeatures 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier 
from sklearn import svm


In [16]:
linear = LinearRegression()

In [17]:
linear.fit(x_train , y_train_label)
y_pred = linear.predict(x_test)
y_pred

array([ 1.57463116,  1.8115326 ,  1.51849601, -0.2016979 ,  2.08370905,
        0.85924333,  1.75853328,  2.06553493,  1.57644322,  1.79809047,
        1.8173428 ,  1.37468985,  1.72441613,  1.53242954,  0.73755567,
        0.85799946,  0.98652965,  0.06708342, -0.08305363,  0.16244132,
       -0.21838934,  1.58717356,  1.3572202 ,  1.84088299,  0.35483605,
        1.40442441,  1.84403018,  0.55629021,  1.23977029,  1.40749766,
        0.74251795,  0.61511558,  1.51646761,  0.57870662,  0.70097139,
        0.24248439,  0.49547044,  1.99586473, -0.1576806 ,  1.33141376,
        0.0573033 ,  0.08835209,  1.4535785 ,  1.60436074,  1.54296878,
        0.55478319,  1.24704683,  1.94267068,  0.06750498,  0.77799386,
        0.45019393,  0.28692047,  1.46269559,  0.13172115,  0.07866225,
        0.31776655,  0.70423735,  0.23390545, -0.20730894,  1.47287929,
        1.50805214,  0.80890454,  0.53455602,  0.4964121 ,  1.50904212,
        1.8800447 ,  0.21418994,  0.6863009 ,  1.65203153,  0.37

In [18]:
from sklearn.metrics import r2_score


In [19]:
r2_score(y_test_label, y_pred)

0.7348976708966981

# logisticregression

In [20]:
lg = LogisticRegression()

In [21]:
lg.fit(x_train, y_train_label)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [22]:
y_pred = lg.predict(x_test)
y_pred

array([2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 0, 0, 0, 0, 2,
       1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 0, 2, 2,
       2, 1, 1, 2, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 0, 0, 1, 2, 2, 1, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 1,
       0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 2, 0, 0, 2, 2, 2,
       2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 2,
       1, 0, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 2, 0,
       1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0,
       2, 0, 2, 2, 1, 0, 1, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 2])

In [23]:
r2_score(y_test_label, y_pred)

0.7276441216522923

# decisiontree

In [24]:
dt = DecisionTreeClassifier()


In [25]:
dt.fit(x_train, y_train_label)

DecisionTreeClassifier()

In [26]:
y_pred = dt.predict(x_test)
y_pred

array([2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 2,
       1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2,
       2, 1, 1, 2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 2,
       0, 0, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1,
       0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0, 2, 2, 2,
       2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 2,
       1, 0, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0,
       2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 2])

In [27]:
r2_score( y_test_label, y_pred)

1.0

In [28]:
x_train.head(3)

Age Gender Air Pollution Alcohol use Dust Allergy chronic Lung Disease  \
29   28      2             1           6            7                    2   
535  53      1             6           8            7                    7   
695  28      2             1           6            7                    2   

    Smoking Chest Pain Coughing of Blood Shortness of Breath Dry Cough  \
29        3          2                 2                   7         7   
535       8          9                 6                   5         7   
695       3          2                 2                   7         7   

    Length Of Stay     glucose pulse  
29               5  190.059466  66.0  
535              6  180.065703  88.0  
695              5  158.415834  88.0

In [ ]:
Age=int(input("entr Age:"))
Gender=int(input("entr gender:"))
AirPollution=int(input("entr airpollution:"))
Alcoholuse=int(input("entr Alcoholuse:"))
DustAllergy=int(input("entr dustallergy:"))
chronicLungDisease=int(input("entr lingdis:"))
Smoking=int(input("entr smoking:"))
ChestPain=int(input("entr chestpain:"))
CoughingofBlood=int(input("entr coughingofblood:"))
ShortnessofBreath=int(input("entr shortnessofbreath:"))
DryCough=int(input("entr drycough:"))
LengthOfStay=int(input("entr lenghtofstay:"))
# Level=int(input("entr Age:"))
glucose=int(input("entr glucose:"))
pulse=int(input("entr pulse:"))

In [ ]:
new_list = np.array([[Age, Gender,AirPollution, Alcoholuse, DustAllergy,
       chronicLungDisease, Smoking, ChestPain, CoughingofBlood,
       ShortnessofBreath, DryCough, LengthOfStay,
       glucose, pulse]])

print(len([Age, Gender,AirPollution, Alcoholuse, DustAllergy,
       chronicLungDisease, Smoking, ChestPain, CoughingofBlood,
       ShortnessofBreath, DryCough, LengthOfStay, Level,
       glucose, pulse]))

In [ ]:
linear.predict(new_list)